apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-gibbon
  labels:
    storage: slow
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: sc-gibbon
  azureFile:
    secretName: azure-secret
    shareName: gibbon
    readOnly: false
  mountOptions:
    - dir_mode=0766
    - file_mode=0766
    - uid=33
    - gid=33
    - mfsymlinks
    - nobrl
